/*Taruh di definisi saat membuat function di postgresql,revisi tabel artikekl_refernsi tambah kolom theyear(text). Hapus limit 100 jika ingin memproses semua data*/

DECLARE
 R IRCI.RECORDS%rowtype;
 TBL_R IRCI.RECORDS%rowtype;
 TBL_AR IRCI.ARTIKEL%rowtype;
 AUTHOR TEXT;
 ID_A UUID;
 ID_R UUID;
 AUTHOR_DESC TEXT[];
 TBL_A IRCI.AUTHORS%rowtype;
 TBL_MRR IRCI.METADATA_REFERENSI_RAW%rowtype;
BEGIN
 FOR R IN
  SELECT * FROM IRCI.RECORDS LIMIT 100
 LOOP
  INSERT INTO IRCI.ARTIKEL VALUES(R.ID_RECORD,R.TITLE,R.SUBJECT_KEYWORDS,R.PUBLISHER);
  FOREACH AUTHOR IN 
  ARRAY R.AUTHOR_CREATOR
  LOOP
   ID_A:=uuid_generate_v4();
   AUTHOR_DESC:=regexp_split_to_array(AUTHOR, ';');
   SELECT * INTO TBL_A FROM IRCI.AUTHORS WHERE AUTHOR_NAME=AUTHOR_DESC[1];
   IF TBL_A.AUTHOR_NAME IS NULL THEN
   	INSERT INTO IRCI.AUTHORS(ID_AUTHORS,AUTHOR_NAME) VALUES(ID_A,AUTHOR_DESC[1]);
    SELECT * INTO TBL_A FROM IRCI.AUTHORS WHERE AUTHOR_NAME=AUTHOR_DESC[1];
   END IF;
   UPDATE IRCI.AUTHORS SET AFFILIATION = ARRAY_APPEND(AFFILIATION,AUTHOR_DESC[2]) WHERE ID_AUTHORS=TBL_A.ID_AUTHORS;
   INSERT INTO IRCI.ARTIKEL_AUTHORS VALUES(uuid_generate_v4(),R.ID_RECORD,TBL_A.ID_AUTHORS);
   FOR TBL_MRR IN
   SELECT DISTINCT MRR.* FROM (SELECT * FROM IRCI.RECORDS RX
   WHERE ID_RECORD=R.ID_RECORD) RX
   JOIN IRCI.IDENTIFIER IDR
   ON IDR.OAI_IDENTIFIER=RX.OAI_IDENTIFIER
   JOIN IRCI.REFERENSI_RAW RR
   ON RR.ID_IDENTIFIER=IDR.ID_IDENTIFIER
   JOIN IRCI.METADATA_REFERENSI_RAW MRR
   ON MRR.ID_REFERENSI_RAW=RR.ID_REFERENSI_RAW
   WHERE MRR.TITLE!='' AND MRR.THEYEAR!=''
   LOOP
    SELECT * INTO TBL_AR FROM IRCI.ARTIKEL WHERE ARTIKEL.TITLE=TBL_MRR.TITLE;
    IF TBL_R.TITLE IS NULL THEN
     INSERT INTO IRCI.ARTIKEL(ID_ARTIKEL,TITLE) VALUES(uuid_generate_v4(),TBL_MRR.TITLE);
     SELECT * INTO TBL_AR FROM IRCI.ARTIKEL WHERE ARTIKEL.TITLE=TBL_MRR.TITLE;
    END IF;
    AUTHOR_DESC:=regexp_split_to_array(TBL_MRR.AUTHORS, ';');
    FOREACH AUTHOR IN ARRAY AUTHOR_DESC
    LOOP
     SELECT * INTO TBL_A FROM IRCI.AUTHORS WHERE AUTHOR_NAME=AUTHOR;
     IF TBL_A.AUTHOR_NAME IS NULL THEN
   	  INSERT INTO IRCI.AUTHORS(ID_AUTHORS,AUTHOR_NAME) VALUES(uuid_generate_v4(),AUTHOR);
      SELECT * INTO TBL_A FROM IRCI.AUTHORS WHERE AUTHOR_NAME=AUTHOR;
     END IF;
      INSERT INTO IRCI.ARTIKEL_AUTHORS VALUES(uuid_generate_v4(),TBL_AR.ID_ARTIKEL,TBL_A.ID_AUTHORS);
    END LOOP;
     INSERT INTO IRCI.ARTIKEL_REFERENSI VALUES(uuid_generate_v4(),R.ID_RECORD,TBL_AR.ID_ARTIKEL,TBL_MRR.THEYEAR);
   END LOOP;
  END LOOP; 
 END LOOP;
 RETURN '1';
END;
